import React, { useState } from 'react';
import { Check, Lock, ShieldCheck, Sparkles, Star, Undo2 } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import { useSubscription } from '../context/SubscriptionContext';

const features = ['Unlimited face scans and comparisons', 'Complete metric breakdown and mesh viewer', 'Personalized routine, products and 30-day roadmap', 'AI Coach, progress timeline and trend analytics'];
export default function Premium() {
  const { isPremium, loading, upgrade, restorePurchase } = useSubscription();
  const navigate = useNavigate();
  const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [success, setSuccess] = useState(false);
  const beginUpgrade = () => { setError(''); setBusy(true); upgrade({ onSuccess: () => { setBusy(false); setSuccess(true); setTimeout(() => navigate('/analysis'), 900); }, onFailure: (message) => { setBusy(false); setError(message); } }); };
  const restore = async () => { setBusy(true); setError(''); try { await restorePurchase(); } catch (e) { setError(e.message); } finally { setBusy(false); } };
  return <div className="max-w-5xl mx-auto space-y-10 pb-16 animate-fade-in text-foreground">
    <section className="relative overflow-hidden rounded-3xl border border-primary/25 bg-gradient-to-br from-primary/20 via-card to-card p-8 md:p-12 text-center">
      <div className="absolute -top-24 left-1/2 h-56 w-56 -translate-x-1/2 rounded-full bg-primary/25 blur-3xl" />
      <div className="relative space-y-5"><span className="inline-flex items-center gap-2 rounded-full border border-primary/30 bg-primary/10 px-3 py-1 text-[10px] font-black tracking-widest text-primary"><Sparkles size={13}/> ASCEND PLUS</span>
        <h1 className="text-3xl md:text-5xl font-black tracking-tight">See the full picture. Build your best routine.</h1>
        <p className="mx-auto max-w-2xl text-sm text-muted-foreground">Your first complete scan is free. Upgrade only after you have seen your score; your saved report unlocks instantly—no rescan and no redirect loop.</p>
        {isPremium ? <button onClick={() => navigate('/analysis')} className="btn-primary-v2 px-6 py-3">View your unlocked report</button> : <button disabled={busy || loading} onClick={beginUpgrade} className="btn-primary-v2 px-7 py-3 shadow-xl shadow-primary/25">{busy ? 'Preparing secure checkout…' : 'Upgrade to Ascend Plus · ₹499'}</button>}</div>
    </section>
    {success && <div className="rounded-2xl border border-emerald-400/30 bg-emerald-500/10 p-4 text-center text-sm font-bold text-emerald-400">Payment verified — your saved report is now unlocked.</div>}
    {error && <div className="rounded-2xl border border-red-400/30 bg-red-500/10 p-4 text-center text-sm text-red-300">{error}</div>}
    <section className="grid md:grid-cols-2 gap-6"><div className="matte-card rounded-3xl border border-border p-7"><h2 className="text-xl font-black">Free preview</h2><p className="mt-2 text-sm text-muted-foreground">One complete scan, Harmony and Potential scores, confidence, date and face preview.</p><div className="mt-6 space-y-3 opacity-55 blur-[2px]"><div className="h-14 rounded-xl bg-secondary"/><div className="h-14 rounded-xl bg-secondary"/><div className="h-14 rounded-xl bg-secondary"/></div></div><div className="rounded-3xl border border-primary/40 bg-gradient-to-b from-primary/15 to-card p-7 shadow-2xl shadow-primary/10"><div className="flex justify-between"><h2 className="text-xl font-black">Ascend Plus</h2><span className="text-2xl font-black">₹499</span></div><p className="text-xs text-muted-foreground mt-1">One-time test-mode purchase during development</p><div className="mt-6 space-y-3">{features.map(f => <div className="flex gap-2 text-sm" key={f}><Check size={17} className="text-emerald-400 shrink-0"/>{f}</div>)}</div><button disabled={busy || isPremium} onClick={beginUpgrade} className="btn-primary-v2 w-full justify-center mt-7 py-3">{isPremium ? 'Your membership is active' : 'Secure checkout'}</button></div></section>
    <section className="grid md:grid-cols-3 gap-4">{[['Secure by design','Payment signatures are verified on the server before access changes.'],['Unlock instantly','Your existing report opens with no rescan or page reload.'],['Restore anywhere','Your subscription is restored automatically on login.']].map(([t,d]) => <div className="rounded-2xl border border-border bg-card p-5" key={t}><ShieldCheck className="text-primary mb-3" size={20}/><h3 className="font-bold">{t}</h3><p className="mt-1 text-xs leading-relaxed text-muted-foreground">{d}</p></div>)}</section>
    <section><h2 className="text-xl font-black mb-4">A report worth unlocking</h2><div className="grid md:grid-cols-3 gap-4"><div className="rounded-2xl overflow-hidden border border-border relative"><img src="/looksmaxing_before.jpg" className="w-full h-36 object-cover" alt="Baseline scan preview"/><span className="absolute inset-0 grid place-items-center bg-card/35 backdrop-blur-[2px] text-xs font-black"><Lock size={15} className="mr-2"/> Locked report preview</span></div><div className="rounded-2xl border border-border p-5 bg-card"><Star className="text-primary mb-3" size={20}/><p className="text-sm font-bold">“The roadmap turned vague goals into a routine I could follow.”</p><span className="mt-3 block text-[10px] text-muted-foreground">— Ascend Plus member</span></div><div className="rounded-2xl border border-border p-5 bg-card"><Sparkles className="text-primary mb-3" size={20}/><h3 className="font-bold">AI Coach preview</h3><p className="mt-2 text-xs leading-relaxed text-muted-foreground blur-[2px]">Your weekly pattern suggests a small routine adjustment to improve consistency…</p></div></div></section>
    <section className="rounded-2xl border border-border p-6"><h2 className="font-black">FAQ</h2><p className="mt-3 text-sm text-muted-foreground"><b className="text-foreground">Can I restore a purchase?</b> Yes. Signing in restores the verified subscription; use the button below if you need to refresh it.</p><button onClick={restore} disabled={busy} className="mt-4 inline-flex items-center gap-2 text-xs font-bold text-primary"><Undo2 size={14}/> Restore purchase</button></section>
  </div>;
}
