// C:\Users\pushk\.gemini\antigravity\scratch\ascend\src\services\engines\aiCoachEngine.js
import { BaseEngine } from './BaseEngine.js';

/**
 * AI Coach Engine
 * Conversational layer. Formulates explanations for queries using outputs
 * generated by other engines to maintain strict safety and domain consistency.
 */
class AICoachEngine extends BaseEngine {
  constructor() {
    super('aiCoachEngine');
  }

  validate(input) {
    if (!input || !input.query) {
      return { isValid: false, errors: ['Input must contain a query string.'] };
    }
    return { isValid: true, errors: [] };
  }

  async execute(input) {
    const { query, recommendations = [], profile = {} } = input;
    this.telemetry.dataSourcesUsed = ['recommendations', 'profile'];

    const q = query.toLowerCase();

    // Check if the query is asking about a specific active recommendation
    const matchingRec = recommendations.find(r => 
      q.includes(r.category.toLowerCase()) || 
      q.includes(r.title.toLowerCase())
    );

    if (matchingRec) {
      return `Based on your biometrics, I recommend you ${matchingRec.title.toLowerCase()}. Specifically, ${matchingRec.description}. This is suggested because: ${matchingRec.reason}. Expect an impact score of ${matchingRec.impact}/5 with a confidence level of ${Math.round(matchingRec.confidence * 100)}%.`;
    }

    // Default conversational fallbacks matching context
    if (q.includes('skincare') || q.includes('skin')) {
      const skinType = profile.skin_type || 'Normal';
      return `For your ${skinType} skin, the recommendation system suggests prioritizing a consistent cleansing and moisturizing cycle. Remember that hydration and UV protection are key foundations.`;
    }

    if (q.includes('sleep') || q.includes('rest')) {
      const sleepLog = profile.sleep_log || { current: 7.0, target: 8.0 };
      return `Your current sleep is logged at ${sleepLog.current}h against a target of ${sleepLog.target}h. Prioritizing rest prevents facial fluid bloating and supports muscle tissue repair.`;
    }

    if (q.includes('posture') || q.includes('stretch')) {
      return "Maintaining neck alignment and performing daily chin-tucks are recommended to define your jaw silhouette and improve overall posture.";
    }

    return "I am your Ascend AI Coach. Ask me about your face symmetry insights, daily routines, fitness schedules, or specific skincare ingredients.";
  }
}

export const aiCoachEngine = new AICoachEngine();
